Repository AutoEverFlipFlick/FlipFlick_BE, pull requests merged in 2025-07, with the labels that each got.

#77 [RELEASE] Main 코드 업데이트
  build.gradle
  src/main/java/com/flipflick/backend/api/admin/service/AdminService.java
  src/main/java/com/flipflick/backend/api/alarm/controller/AlarmController.java
  src/main/java/com/flipflick/backend/api/alarm/dto/AlarmDTO.java
  src/main/java/com/flipflick/backend/api/alarm/entity/Alarm.java
  src/main/java/com/flipflick/backend/api/alarm/event/AlarmEvent.java
  src/main/java/com/flipflick/backend/api/alarm/repository/AlarmRepository.java
  src/main/java/com/flipflick/backend/api/alarm/service/AlarmService.java
  src/main/java/com/flipflick/backend/api/debate/controller/DebateCommentController.java
  src/main/java/com/flipflick/backend/api/debate/dto/DebateCommentRequestDto.java
  src/main/java/com/flipflick/backend/api/debate/dto/DebateCommentResponseDto.java
  src/main/java/com/flipflick/backend/api/debate/entity/DebateComment.java
  src/main/java/com/flipflick/backend/api/debate/repository/DebateCommentRepository.java
  src/main/java/com/flipflick/backend/api/debate/service/DebateCommentService.java
  src/main/java/com/flipflick/backend/api/follow/controller/FollowController.java
  src/main/java/com/flipflick/backend/api/member/entity/Member.java
  src/main/java/com/flipflick/backend/api/movie/controller/MovieController.java
  src/main/java/com/flipflick/backend/api/passwordReset/controller/PasswordResetController.java
  src/main/java/com/flipflick/backend/api/passwordReset/dto/ResetPasswordRequestDto.java
  src/main/java/com/flipflick/backend/api/passwordReset/dto/SendResetLinkRequestDto.java
  src/main/java/com/flipflick/backend/api/passwordReset/entity/PasswordReset.java
  src/main/java/com/flipflick/backend/api/passwordReset/repository/PasswordResetRepository.java
  src/main/java/com/flipflick/backend/api/passwordReset/service/PasswordResetService.java
  src/main/java/com/flipflick/backend/api/recommendation/controller/RecommendationController.java
  src/main/java/com/flipflick/backend/api/recommendation/dto/RecommendationDataDto.java
  src/main/java/com/flipflick/backend/api/recommendation/dto/SimilarityBatchDto.java
  src/main/java/com/flipflick/backend/api/recommendation/entity/UserSimilarity.java
  src/main/java/com/flipflick/backend/api/recommendation/repository/UserSimilarityRepository.java
  src/main/java/com/flipflick/backend/api/recommendation/service/RecommendationService.java
  src/main/java/com/flipflick/backend/api/review/dto/ReviewResponseDto.java
  src/main/java/com/flipflick/backend/api/review/repository/ReviewRepository.java
  src/main/java/com/flipflick/backend/api/review/service/ReviewService.java
  src/main/java/com/flipflick/backend/common/config/resttemplate/RestTemplateConfig.java
  src/main/java/com/flipflick/backend/common/config/security/SecurityConfig.java
  src/main/java/com/flipflick/backend/common/response/ErrorStatus.java
  src/main/java/com/flipflick/backend/common/response/SuccessStatus.java
  src/test/java/com/flipflick/backend/BackendApplicationTests.java
Labels: RELEASE

#82 [FEAT] 로그아웃 기능 구현
  src/main/java/com/flipflick/backend/api/member/controller/MemberController.java
  src/main/java/com/flipflick/backend/api/member/service/MemberService.java
  src/main/java/com/flipflick/backend/common/config/security/SecurityConfig.java
  src/main/java/com/flipflick/backend/common/response/SuccessStatus.java
Labels: FEAT

#95 [RELEASE] Main 코드 업데이트
  src/main/java/com/flipflick/backend/api/debate/dto/DebateResponseDto.java
  src/main/java/com/flipflick/backend/api/debate/repository/DebateCommentRepository.java
  src/main/java/com/flipflick/backend/api/debate/service/DebateService.java
  src/main/java/com/flipflick/backend/api/follow/controller/FollowController.java
  src/main/java/com/flipflick/backend/api/follow/repository/FollowRepository.java
  src/main/java/com/flipflick/backend/api/follow/service/FollowService.java
Labels: RELEASE

#94 [FIX] 알림생성
  src/main/java/com/flipflick/backend/api/admin/service/AdminService.java
  src/main/java/com/flipflick/backend/api/alarm/controller/AlarmController.java
  src/main/java/com/flipflick/backend/api/alarm/entity/Alarm.java
  src/main/java/com/flipflick/backend/api/alarm/service/AlarmService.java
  src/main/java/com/flipflick/backend/api/debate/service/DebateCommentService.java
  src/main/java/com/flipflick/backend/api/debate/service/DebateService.java
  src/main/java/com/flipflick/backend/api/follow/repository/FollowRepository.java
  src/main/java/com/flipflick/backend/api/member/entity/Member.java
  src/main/java/com/flipflick/backend/api/member/service/PopcornScoreService.java
  src/main/java/com/flipflick/backend/api/playlist/service/PlayListService.java
  src/main/java/com/flipflick/backend/api/review/service/ReviewService.java
  src/main/java/com/flipflick/backend/common/response/AlarmMessage.java
Labels: FIX

#97 [FEAT] 현재 상영중인 영화 조회 구현
  build.gradle
  src/main/java/com/flipflick/backend/BackendApplication.java
  src/main/java/com/flipflick/backend/api/movie/controller/MovieController.java
  src/main/java/com/flipflick/backend/api/movie/dto/BoxOfficeMovieDTO.java
  src/main/java/com/flipflick/backend/api/movie/dto/BoxOfficeResponseDTO.java
  src/main/java/com/flipflick/backend/api/movie/scheduler/BoxOfficeCacheScheduler.java
  src/main/java/com/flipflick/backend/api/movie/service/MovieService.java
  src/main/java/com/flipflick/backend/common/config/redis/RedisConfig.java
  src/main/java/com/flipflick/backend/common/config/security/SecurityConfig.java
  src/main/java/com/flipflick/backend/common/config/webclient/WebClientConfig.java
  src/main/java/com/flipflick/backend/common/response/SuccessStatus.java
Labels: FEAT

#98 [RELEASE] Main 코드 업데이트
  build.gradle
  src/main/java/com/flipflick/backend/BackendApplication.java
  src/main/java/com/flipflick/backend/api/admin/service/AdminService.java
  src/main/java/com/flipflick/backend/api/alarm/controller/AlarmController.java
  src/main/java/com/flipflick/backend/api/alarm/entity/Alarm.java
  src/main/java/com/flipflick/backend/api/alarm/service/AlarmService.java
  src/main/java/com/flipflick/backend/api/debate/service/DebateCommentService.java
  src/main/java/com/flipflick/backend/api/debate/service/DebateService.java
  src/main/java/com/flipflick/backend/api/follow/repository/FollowRepository.java
  src/main/java/com/flipflick/backend/api/member/entity/Member.java
  src/main/java/com/flipflick/backend/api/member/service/PopcornScoreService.java
  src/main/java/com/flipflick/backend/api/movie/controller/MovieController.java
  src/main/java/com/flipflick/backend/api/movie/dto/BoxOfficeMovieDTO.java
  src/main/java/com/flipflick/backend/api/movie/dto/BoxOfficeResponseDTO.java
  src/main/java/com/flipflick/backend/api/movie/scheduler/BoxOfficeCacheScheduler.java
  src/main/java/com/flipflick/backend/api/movie/service/MovieService.java
  src/main/java/com/flipflick/backend/api/playlist/service/PlayListService.java
  src/main/java/com/flipflick/backend/api/review/service/ReviewService.java
  src/main/java/com/flipflick/backend/common/config/redis/RedisConfig.java
  src/main/java/com/flipflick/backend/common/config/security/SecurityConfig.java
  src/main/java/com/flipflick/backend/common/config/webclient/WebClientConfig.java
  src/main/java/com/flipflick/backend/common/response/AlarmMessage.java
  src/main/java/com/flipflick/backend/common/response/SuccessStatus.java
Labels: RELEASE

#102 [FEAT] 회원 탈퇴
  src/main/java/com/flipflick/backend/api/debate/repository/DebateCommentRepository.java
  src/main/java/com/flipflick/backend/api/debate/repository/DebateLikeHateRepository.java
  src/main/java/com/flipflick/backend/api/debate/repository/DebateRepository.java
  src/main/java/com/flipflick/backend/api/debate/service/DebateService.java
  src/main/java/com/flipflick/backend/api/follow/repository/FollowRepository.java
  src/main/java/com/flipflick/backend/api/follow/service/FollowService.java
  src/main/java/com/flipflick/backend/api/member/controller/MemberController.java
  src/main/java/com/flipflick/backend/api/member/dto/MemberSignupRequestDto.java
  src/main/java/com/flipflick/backend/api/member/entity/Member.java
  src/main/java/com/flipflick/backend/api/member/repository/MemberRepository.java
  src/main/java/com/flipflick/backend/api/member/service/KakaoAuthService.java
  src/main/java/com/flipflick/backend/api/member/service/MemberService.java
  src/main/java/com/flipflick/backend/api/member/service/NaverAuthService.java
  src/main/java/com/flipflick/backend/api/member/service/PopcornScoreService.java
  src/main/java/com/flipflick/backend/api/movie/service/MovieService.java
  src/main/java/com/flipflick/backend/api/passwordReset/service/PasswordResetService.java
  src/main/java/com/flipflick/backend/api/playlist/repository/PlayListRepository.java
  src/main/java/com/flipflick/backend/api/playlist/service/PlayListService.java
  src/main/java/com/flipflick/backend/api/report/service/ReportService.java
  src/main/java/com/flipflick/backend/api/review/repository/ReviewRepository.java
  src/main/java/com/flipflick/backend/api/review/service/ReviewService.java
  src/main/java/com/flipflick/backend/api/search/service/SearchService.java
  src/main/java/com/flipflick/backend/common/response/SuccessStatus.java
Labels: FEAT

#104 [RELEASE] Main 코드 업데이트
  src/main/java/com/flipflick/backend/api/debate/repository/DebateCommentRepository.java
  src/main/java/com/flipflick/backend/api/debate/repository/DebateLikeHateRepository.java
  src/main/java/com/flipflick/backend/api/debate/repository/DebateRepository.java
  src/main/java/com/flipflick/backend/api/debate/service/DebateService.java
  src/main/java/com/flipflick/backend/api/follow/repository/FollowRepository.java
  src/main/java/com/flipflick/backend/api/follow/service/FollowService.java
  src/main/java/com/flipflick/backend/api/member/controller/MemberController.java
  src/main/java/com/flipflick/backend/api/member/dto/MemberSignupRequestDto.java
  src/main/java/com/flipflick/backend/api/member/entity/Member.java
  src/main/java/com/flipflick/backend/api/member/repository/MemberRepository.java
  src/main/java/com/flipflick/backend/api/member/service/KakaoAuthService.java
  src/main/java/com/flipflick/backend/api/member/service/MemberService.java
  src/main/java/com/flipflick/backend/api/member/service/NaverAuthService.java
  src/main/java/com/flipflick/backend/api/member/service/PopcornScoreService.java
  src/main/java/com/flipflick/backend/api/movie/service/MovieService.java
  src/main/java/com/flipflick/backend/api/passwordReset/service/PasswordResetService.java
  src/main/java/com/flipflick/backend/api/playlist/repository/PlayListRepository.java
  src/main/java/com/flipflick/backend/api/playlist/service/PlayListService.java
  src/main/java/com/flipflick/backend/api/report/service/ReportService.java
  src/main/java/com/flipflick/backend/api/review/dto/ReviewResponseDto.java
  src/main/java/com/flipflick/backend/api/review/repository/ReviewRepository.java
  src/main/java/com/flipflick/backend/api/review/service/ReviewService.java
  src/main/java/com/flipflick/backend/api/search/service/SearchService.java
  src/main/java/com/flipflick/backend/common/config/security/SecurityConfig.java
  src/main/java/com/flipflick/backend/common/jwt/JWTFilter.java
  src/main/java/com/flipflick/backend/common/response/SuccessStatus.java
Labels: RELEASE

#111 [RELEASE] Main 코드 업데이트
  src/main/java/com/flipflick/backend/api/debate/controller/DebateCommentController.java
  src/main/java/com/flipflick/backend/api/debate/entity/Debate.java
  src/main/java/com/flipflick/backend/api/debate/repository/DebateCommentRepository.java
  src/main/java/com/flipflick/backend/api/debate/service/DebateCommentService.java
  src/main/java/com/flipflick/backend/api/debate/service/DebateService.java
  src/main/java/com/flipflick/backend/api/report/entity/Report.java
Labels: RELEASE

#117 [FIX] playlistDto 수정
  src/main/java/com/flipflick/backend/api/movie/controller/MovieController.java
  src/main/java/com/flipflick/backend/api/playlist/controller/PlayListController.java
  src/main/java/com/flipflick/backend/api/playlist/dto/PlayListRequestDto.java
  src/main/java/com/flipflick/backend/api/playlist/dto/PlayListResponseDto.java
  src/main/java/com/flipflick/backend/api/playlist/service/PlayListService.java
Labels: FIX

#118 [RELEASE] Main 코드 업데이트
  src/main/java/com/flipflick/backend/api/movie/controller/MovieController.java
  src/main/java/com/flipflick/backend/api/playlist/controller/PlayListController.java
  src/main/java/com/flipflick/backend/api/playlist/dto/PlayListRequestDto.java
  src/main/java/com/flipflick/backend/api/playlist/dto/PlayListResponseDto.java
  src/main/java/com/flipflick/backend/api/playlist/service/PlayListService.java
Labels: RELEASE

#123 [RELEASE] Main 코드 업데이트
  src/main/java/com/flipflick/backend/api/recommendation/controller/RecommendationController.java
  src/main/java/com/flipflick/backend/api/recommendation/service/RecommendationService.java
  src/main/java/com/flipflick/backend/api/review/repository/ReviewRepository.java
Labels: RELEASE
